require('dotenv').config();

/**
 * Formats structured analysis into a clean, professional WhatsApp message with emojis and markdown.
 * 
 * @param {Object} analysis
 * @returns {string} Formatted WhatsApp message text
 */
function formatWhatsAppMessage(analysis) {
  const asset = analysis.asset || 'BTC/USDT';
  const session = analysis.session_name || 'Market Session';
  const bias = (analysis.bias || 'NEUTRAL').toUpperCase();
  const model = analysis.model_used || 'Gemini 3.8 Flash';
  const levels = analysis.key_levels || {};
  const scenario = analysis.primary_scenario || {};

  const biasEmoji = bias === 'BULLISH' ? '🟢 BULLISH' : (bias === 'BEARISH' ? '🔴 BEARISH' : '🟡 NEUTRAL');

  let targetsStr = 'N/A';
  if (Array.isArray(scenario.targets) && scenario.targets.length > 0) {
    targetsStr = scenario.targets.map(t => `$${Number(t).toLocaleString()}`).join(', ');
  }

  const dateStr = new Date(analysis.timestamp || Date.now()).toISOString().replace('T', ' ').slice(0, 16) + ' UTC';

  return `📊 *AUCTION MARKET INTEL // AI REPORT*
━━━━━━━━━━━━━━━━━━━━
🎯 *Asset:* ${asset}
⏰ *Session:* ${session} (${dateStr})
🤖 *Engine:* ${model}
🧭 *Bias:* *${biasEmoji}*

📈 *Key Structural Levels:*
• *POC (Point of Control):* $${levels.poc ? Number(levels.poc).toLocaleString() : '--'}
• *VAH (Value Area High):* $${levels.vah ? Number(levels.vah).toLocaleString() : '--'}
• *VAL (Value Area Low):* $${levels.val ? Number(levels.val).toLocaleString() : '--'}
• *Support:* $${levels.support ? Number(levels.support).toLocaleString() : '--'} | *Resistance:* $${levels.resistance ? Number(levels.resistance).toLocaleString() : '--'}
• *Invalidation Risk:* 🛑 $${analysis.invalidation_level ? Number(analysis.invalidation_level).toLocaleString() : '--'}

📝 *Price Action & Market Structure:*
${analysis.price_action_summary || 'Acceptance and rotation within value boundaries.'}

🎯 *Trade Plan & Execution:*
• *Direction:* ${scenario.direction || 'Mean Reversion'}
• *Trigger:* ${scenario.trigger || 'Reclaim and hold of volume anchor.'}
• *Target Levels:* ${targetsStr}

━━━━━━━━━━━━━━━━━━━━
⚡ _Automated report generated by TekFX AI_`;
}

/**
 * Dispatches WhatsApp message using CallMeBot, Twilio, or generic webhook.
 * 
 * @param {Object} analysis - Analysis record
 * @returns {Promise<{success: boolean, provider: string, message?: string}>}
 */
async function sendWhatsAppAnalysis(analysis) {
  const recipient = process.env.WHATSAPP_PHONE || '+212648863582';
  const cleanPhone = recipient.replace(/[^0-9]/g, ''); // e.g. 212648863582
  const textMessage = formatWhatsAppMessage(analysis);

  console.log(`[WhatsApp] Preparing notification for: +${cleanPhone}`);

  // Provider 1: CallMeBot (Free, zero-signup instant WhatsApp gateway)
  const callmebotKey = process.env.CALLMEBOT_API_KEY;
  if (callmebotKey) {
    console.log('[WhatsApp] Sending via CallMeBot gateway...');
    try {
      const url = `https://api.callmebot.com/whatsapp.php?phone=${cleanPhone}&text=${encodeURIComponent(textMessage)}&apikey=${callmebotKey}`;
      const response = await fetch(url);
      const body = await response.text();
      console.log('[WhatsApp] CallMeBot response:', body);
      return { success: true, provider: 'callmebot', response: body };
    } catch (err) {
      console.error('[WhatsApp] CallMeBot dispatch failed:', err.message);
    }
  }

  // Provider 2: Twilio WhatsApp API
  const twilioSid = process.env.TWILIO_ACCOUNT_SID;
  const twilioToken = process.env.TWILIO_AUTH_TOKEN;
  const twilioFrom = process.env.TWILIO_WHATSAPP_NUMBER || 'whatsapp:+14155238886'; // default Twilio sandbox

  if (twilioSid && twilioToken) {
    console.log('[WhatsApp] Sending via Twilio API...');
    try {
      const twilioUrl = `https://api.twilio.com/2010-04-01/Accounts/${twilioSid}/Messages.json`;
      const formData = new URLSearchParams();
      formData.append('From', twilioFrom.startsWith('whatsapp:') ? twilioFrom : `whatsapp:${twilioFrom}`);
      formData.append('To', `whatsapp:+${cleanPhone}`);
      formData.append('Body', textMessage);

      const authHeader = 'Basic ' + Buffer.from(`${twilioSid}:${twilioToken}`).toString('base64');
      const response = await fetch(twilioUrl, {
        method: 'POST',
        headers: {
          'Authorization': authHeader,
          'Content-Type': 'application/x-www-form-urlencoded'
        },
        body: formData.toString()
      });

      const resJson = await response.json();
      console.log('[WhatsApp] Twilio message status:', resJson.status, resJson.sid);
      return { success: response.ok, provider: 'twilio', data: resJson };
    } catch (err) {
      console.error('[WhatsApp] Twilio dispatch failed:', err.message);
    }
  }

  // Provider 3: Generic Custom Webhook
  const webhookUrl = process.env.WHATSAPP_WEBHOOK_URL;
  if (webhookUrl) {
    console.log('[WhatsApp] Sending via custom WhatsApp webhook...');
    try {
      const response = await fetch(webhookUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          phone: `+${cleanPhone}`,
          message: textMessage,
          analysis
        })
      });
      const resData = await response.text();
      return { success: response.ok, provider: 'webhook', data: resData };
    } catch (err) {
      console.error('[WhatsApp] Webhook dispatch failed:', err.message);
    }
  }

  // If no credentials configured yet
  console.log('------------------------------------------------------');
  console.log('[WhatsApp Notification Preview for +' + cleanPhone + ']:');
  console.log(textMessage);
  console.log('------------------------------------------------------');
  console.log('[WhatsApp] Note: Set CALLMEBOT_API_KEY or TWILIO credentials in Railway variables to enable instant mobile delivery.');

  return {
    success: false,
    provider: 'none',
    preview: textMessage,
    recipient: `+${cleanPhone}`
  };
}

module.exports = {
  sendWhatsAppAnalysis,
  formatWhatsAppMessage
};
