require('dotenv').config();

/**
 * Formats structured analysis into a clean, professional WhatsApp message with emojis and markdown.
 * 
 * @param {Object} analysis
 * @returns {string} Formatted WhatsApp message text
 */
function formatWhatsAppMessage(analysis) {
  const asset = analysis.asset || 'BTC/USDT';
  const session = analysis.session_name || 'Market Session';
  const bias = (analysis.bias || 'NEUTRAL').toUpperCase();
  const model = analysis.model_used || 'Gemini 3.8 Flash';
  const levels = analysis.key_levels || {};
  const scenario = analysis.primary_scenario || {};

  const biasEmoji = bias === 'BULLISH' ? '🟢 BULLISH' : (bias === 'BEARISH' ? '🔴 BEARISH' : '🟡 NEUTRAL');

  let targetsStr = 'N/A';
  if (Array.isArray(scenario.targets) && scenario.targets.length > 0) {
    targetsStr = scenario.targets.map(t => `$${Number(t).toLocaleString()}`).join(', ');
  }

  const dateStr = new Date(analysis.timestamp || Date.now()).toISOString().replace('T', ' ').slice(0, 16) + ' UTC';

  return `📊 *AUCTION MARKET INTEL // AI REPORT*
━━━━━━━━━━━━━━━━━━━━
🎯 *Asset:* ${asset}
⏰ *Session:* ${session} (${dateStr})
🤖 *Engine:* ${model}
🧭 *Bias:* *${biasEmoji}*

📈 *Key Structural Levels:*
• *POC (Point of Control):* $${levels.poc ? Number(levels.poc).toLocaleString() : '--'}
• *VAH (Value Area High):* $${levels.vah ? Number(levels.vah).toLocaleString() : '--'}
• *VAL (Value Area Low):* $${levels.val ? Number(levels.val).toLocaleString() : '--'}
• *Support:* $${levels.support ? Number(levels.support).toLocaleString() : '--'} | *Resistance:* $${levels.resistance ? Number(levels.resistance).toLocaleString() : '--'}
• *Invalidation Risk:* 🛑 $${analysis.invalidation_level ? Number(analysis.invalidation_level).toLocaleString() : '--'}

📝 *Price Action & Market Structure:*
${analysis.price_action_summary || 'Acceptance and rotation within value boundaries.'}

🎯 *Trade Plan & Execution:*
• *Direction:* ${scenario.direction || 'Mean Reversion'}
• *Trigger:* ${scenario.trigger || 'Reclaim and hold of volume anchor.'}
• *Target Levels:* ${targetsStr}

━━━━━━━━━━━━━━━━━━━━
⚡ _Automated report generated by TekFX AI_`;
}

/**
 * Returns a direct one-click WhatsApp URL (wa.me) that opens the user's personal WhatsApp
 * with the pre-filled analysis report ready to send to themselves with one tap.
 */
function getWhatsAppDirectUrl(analysis, phone = '+212648863582') {
  const cleanPhone = (phone || process.env.WHATSAPP_PHONE || '212648863582').replace(/[^0-9]/g, '');
  const textMessage = formatWhatsAppMessage(analysis);
  return `https://wa.me/${cleanPhone}?text=${encodeURIComponent(textMessage)}`;
}

/**
 * Dispatches notification using Green-API (Personal WhatsApp QR code), Telegram, CallMeBot, or Twilio.
 * 
 * @param {Object} analysis - Analysis record
 * @returns {Promise<{success: boolean, provider: string, message?: string, directUrl?: string}>}
 */
async function sendWhatsAppAnalysis(analysis) {
  const recipient = process.env.WHATSAPP_PHONE || '+212648863582';
  const cleanPhone = recipient.replace(/[^0-9]/g, ''); // 212648863582
  const textMessage = formatWhatsAppMessage(analysis);
  const directUrl = getWhatsAppDirectUrl(analysis, cleanPhone);

  console.log(`[Notification] Preparing dispatch for: +${cleanPhone}`);

  // Provider 1: Green-API (Uses your personal WhatsApp account by scanning a QR code)
  const greenInstance = process.env.GREEN_API_INSTANCE_ID;
  const greenToken = process.env.GREEN_API_TOKEN;
  if (greenInstance && greenToken) {
    console.log('[Notification] Sending via your Personal WhatsApp (Green-API)...');
    try {
      const url = `https://api.green-api.com/waInstance${greenInstance}/sendMessage/${greenToken}`;
      const response = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          chatId: `${cleanPhone}@c.us`,
          message: textMessage
        })
      });
      const resJson = await response.json();
      console.log('[Notification] Green-API result:', resJson);
      return { success: response.ok, provider: 'green-api', data: resJson, directUrl };
    } catch (err) {
      console.error('[Notification] Green-API failed:', err.message);
    }
  }

  // Provider 2: Telegram Bot (The #1 free, instant, 100% reliable alert system for traders)
  const tgToken = process.env.TELEGRAM_BOT_TOKEN;
  const tgChatId = process.env.TELEGRAM_CHAT_ID;
  if (tgToken && tgChatId) {
    console.log('[Notification] Sending via Telegram Bot to personal chat...');
    try {
      const url = `https://api.telegram.org/bot${tgToken}/sendMessage`;
      const response = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          chat_id: tgChatId,
          text: textMessage,
          parse_mode: 'Markdown'
        })
      });
      const resJson = await response.json();
      console.log('[Notification] Telegram message status:', resJson.ok);
      return { success: resJson.ok, provider: 'telegram', data: resJson, directUrl };
    } catch (err) {
      console.error('[Notification] Telegram dispatch failed:', err.message);
    }
  }

  // Provider 3: CallMeBot WhatsApp Gateway
  const callmebotKey = process.env.CALLMEBOT_API_KEY;
  if (callmebotKey) {
    console.log('[Notification] Sending via CallMeBot gateway...');
    try {
      const url = `https://api.callmebot.com/whatsapp.php?phone=${cleanPhone}&text=${encodeURIComponent(textMessage)}&apikey=${callmebotKey}`;
      const response = await fetch(url);
      const body = await response.text();
      console.log('[Notification] CallMeBot response:', body);
      return { success: true, provider: 'callmebot', response: body, directUrl };
    } catch (err) {
      console.error('[Notification] CallMeBot dispatch failed:', err.message);
    }
  }

  // Provider 4: Twilio WhatsApp API
  const twilioSid = process.env.TWILIO_ACCOUNT_SID;
  const twilioToken = process.env.TWILIO_AUTH_TOKEN;
  const twilioFrom = process.env.TWILIO_WHATSAPP_NUMBER || 'whatsapp:+14155238886';

  if (twilioSid && twilioToken) {
    console.log('[Notification] Sending via Twilio API...');
    try {
      const twilioUrl = `https://api.twilio.com/2010-04-01/Accounts/${twilioSid}/Messages.json`;
      const formData = new URLSearchParams();
      formData.append('From', twilioFrom.startsWith('whatsapp:') ? twilioFrom : `whatsapp:${twilioFrom}`);
      formData.append('To', `whatsapp:+${cleanPhone}`);
      formData.append('Body', textMessage);

      const authHeader = 'Basic ' + Buffer.from(`${twilioSid}:${twilioToken}`).toString('base64');
      const response = await fetch(twilioUrl, {
        method: 'POST',
        headers: {
          'Authorization': authHeader,
          'Content-Type': 'application/x-www-form-urlencoded'
        },
        body: formData.toString()
      });

      const resJson = await response.json();
      console.log('[Notification] Twilio message status:', resJson.status, resJson.sid);
      return { success: response.ok, provider: 'twilio', data: resJson, directUrl };
    } catch (err) {
      console.error('[Notification] Twilio dispatch failed:', err.message);
    }
  }

  // Default: Direct wa.me link & console preview
  console.log('------------------------------------------------------');
  console.log('[WhatsApp One-Click Direct Link for +' + cleanPhone + ']:');
  console.log(directUrl);
  console.log('------------------------------------------------------');

  return {
    success: false,
    provider: 'none',
    preview: textMessage,
    directUrl,
    recipient: `+${cleanPhone}`
  };
}

module.exports = {
  sendWhatsAppAnalysis,
  formatWhatsAppMessage,
  getWhatsAppDirectUrl
};
